Controllers/InvoiceController.cs
using Azure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Party_Management.DTOs;
using Party_Management.Models;
using Party_Management.ServiceContract;
using Party_Management.ViewModels;
using Rotativa.AspNetCore;
using Rotativa.AspNetCore.Options;
using ServiceContract;

namespace Party_Management.Controllers
{
    [Route("[controller]/[action]")]
    //[IgnoreAntiforgeryToken]
    public class InvoiceController : Controller
    {
        private readonly IInvoiceService _invoiceService;
        private readonly IProductAssignmentService _productAssignmentService;
        private readonly IPartyService _partyService;

        public InvoiceController(IInvoiceService invoiceService, IProductAssignmentService productAssignmentService, IPartyService partyService)
        {
            _invoiceService = invoiceService;
            _productAssignmentService = productAssignmentService;
            _partyService = partyService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<InvoiceResponseDTO> allInvoices = _invoiceService.GetAllInvoice();
            return View(allInvoices);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(int? partyId)
        {
            ViewBag.Party = _partyService.GetAllParty().Select(p => new
            {
                Text = p.PartyName,
                Value = p.PartyId.ToString()
            });
            InvoiceViewModel invoiceView;

            if (partyId.HasValue)
            {
                IEnumerable<ProductResponseDTO> products;
                try
                {
                    products = _productAssignmentService.GetAssignProductByPartyID(partyId.Value);
                    ViewBag.products = products.Select(p => new
                    {
                        ProductName = p.ProductName,
                        ProductId = p.ProductId.ToString(),
                        Price = p.Price.ToString("F2") // Format price as needed
                    });
                    invoiceView = new InvoiceViewModel()
                    {
                        PartyId = partyId.Value,
                        PartyName = _partyService.GetPartyById(partyId.Value).PartyName
                    };
                }
                catch(Exception ex)
                {
                    TempData["ErrorMessage"] = "The party ID provided is invalid or does not exist." + ex;
                    return RedirectToAction("Error", "Home");
                }
            }
            else
            {
                invoiceView = new InvoiceViewModel();
                ViewBag.Products = Enumerable.Empty<SelectListItem>();
            }
            return View(invoiceView);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult CreateInvoice([FromBody] List<InvoiceRequestDTO> invoiceData)
        {
            Console.WriteLine("Enter in Controller");
            if (!ModelState.IsValid)
            {
                return BadRequest("Invalid invoice data. ");
            }
            Console.WriteLine(invoiceData);
            if (invoiceData == null || invoiceData.Count() == 0)
            {
                Console.WriteLine(invoiceData.Count());
                return BadRequest("Invalid invoice data. ");
            }

            InvoiceResponseDTO invoiceResponse = _invoiceService.AddInvoice(invoiceData, invoiceData[0].PartyId);

            return Ok(new { Message = "Invoice created successfully!", Total = invoiceResponse.Total.ToString(), TotalItem = invoiceResponse.ProductCount.ToString(), invoiceId = invoiceResponse.InvoiceId });
        }

        [HttpGet]
        public IActionResult Details(int invoiceId)
        {
            if (invoiceId <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(invoiceId));
            }

            InvoiceDetailDTO invoiceDetail = _invoiceService.GetInvoiceDetailsByInvoiceId(invoiceId);

            return View(invoiceDetail);
        }

        [HttpGet]
        public IActionResult InvoiceByParty(int partyId)
        {
            if (partyId < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(partyId));
            }

            IEnumerable<InvoiceResponseDTO> invoiceDetsilByParty = _invoiceService.GetInvoiceByPartyId(partyId);

            return View(invoiceDetsilByParty);
        }

        [HttpGet]
        public IActionResult InvoicePDF(int invoiceId)
        {
            if (invoiceId <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(invoiceId));
            }

            InvoiceDetailDTO invoiceDetail = _invoiceService.GetInvoiceDetailsByInvoiceId(invoiceId);

            //return View(invoiceDetail);

            return new ViewAsPdf("InvoicePDF", invoiceDetail, ViewData)
            {
                PageMargins = new Margins() { Top = 15, Bottom = 15, Left = 15, Right = 15 },
            };
        }



    }
}

Controllers/ProductRateController.cs
using Microsoft.AspNetCore.Mvc;
using Party_Management.DTOs;
using Party_Management.ServiceContract;

namespace Party_Management.Controllers
{
    [Route("[controller]/[action]")]
    public class ProductRateController : Controller
    {
        private readonly IProductRateService _productRateService;


        public ProductRateController(IProductRateService productRateService)
        {
            _productRateService = productRateService;
        }

        public IActionResult List()
        {
            IEnumerable<ProductRateResponseDTO> producatRate = _productRateService.GetProductRate();
            return View(producatRate);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Party Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Party_Management.styles.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.5/css/dataTables.dataTables.css" /> 
    <script src="https://cdn.datatables.net/2.1.5/js/dataTables.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" asp-area="" asp-controller="Party" asp-action="Index">Party Management</a>

                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Party" asp-action="Index">Party</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ProductRate" asp-action="List">Product Rate History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ProductAssignment" asp-action="ProductAssignmentList">Assign Product History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Invoice" asp-action="Index">Invoice</a>
                        </li>
                    </ul>
                      

                    @{
                        if (User.Identity.IsAuthenticated)
                        {
                            <p class="text-center my-auto"> @User.Identity?.Name </p>
                            <a asp-controller="Account" asp-action="Logout"><button class="btn btn-outline-danger mx-2">Logout</button></a>
                        }
                        else
                        {
                            <a asp-controller="Account" asp-action="Register"> <button class="btn btn-outline-success mx-2">Register</button></a>
                            <a asp-controller="Account" asp-action="Login"> <button class="btn btn-outline-success mx-2">Login</button></a>
                        }
                    }
                       
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Party Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

   @*  <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>